name: Build Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'templates/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template
    defaults:
      run:
        working-directory: templates/${{ matrix.template }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Install
        run: pnpm install -r

      - name: 🏗 Run build
        run: pnpm run build
