name: Lint and typecheck

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'packages/**'
      - '.github/actions/**'
      - '.github/workflows/lint-typecheck.yml'
      - 'pnpm.lock'
      - '.prettier*'
      - '.eslint*'
      - 'jest.config.js'
      - 'tsconfig.json'
      - 'turbo.json'
      - 'config'
      - 'scripts'
      - 'patches'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'packages/**'
      - '.github/actions/**'
      - '.github/workflows/**'
      - 'pnpm.lock'
      - '.prettier*'
      - '.eslint*'
      - 'jest.config.js'
      - 'tsconfig.json'
      - 'turbo.json'
      - 'config'
      - 'scripts'
      - 'patches'

# Add concurrency to cancel redundant runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Install
        run: pnpm install -r

      - name: ♻️ Restore packages cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: packages-cache-${{ runner.os }}-${{ hashFiles('pnpm.lock') }}

      - name: 🏗 Run build
        run: pnpm run build

      - name: 🔬 Linter
        run: pnpm run lint

      - name: 🕵️ Typecheck
        run: pnpm run typecheck:all

  notify-failure:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: [lint-typecheck]
    if: ${{ github.event_name == 'push' && failure() }}

    steps:
      - name: Send Discord Notification
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.X_GITHUB_READ_ACTIONS_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          description: ${{ github.event.number && format('https://github.com/udecode/plate/pull/{0}', github.event.number) || 'Push' }}
