name: Registry

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/registry.yml'
      - 'apps/www/src/registry/**'

jobs:
  update-registry:
    name: Update Registry
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Install
        run: pnpm install -r

      - name: ♻️ Restore packages cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: packages-cache-${{ runner.os }}-${{ hashFiles('pnpm.lock') }}

      - name: 🏗 Build Registry
        run: pnpm run build:registry && pnpm run build:tw

      - name: ◻️ Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Update Registry'
          body: |
            Update Registry.
          commit-message: docs
          committer: GitHub <noreply@github.com>
          branch: registry
          delete-branch: true
          add-paths: |
            apps/www/**/*
