name: ReleaseOrVersionPR

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release and changelog
    runs-on: ubuntu-latest
    # Basic security: the release job can only be executed from this repo and from the main branch
    if: ${{ github.repository == 'udecode/plate' && contains('refs/heads/main',github.ref)}}

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          # To run comparison we need more than the latest commit
          fetch-depth: 0

      - name: ♻️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Install
        run: pnpm install -

      # @link https://github.com/changesets/action
      - name: 🦋 Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          cwd: ${{ github.workspace }}
          title: '[Release] Version packages'
          publish: pnpm release
          # Optional, might be used in conjunction with GITHUB_TOKEN to
          # allow running the workflows on a Version package action.
          # Be aware of security implications.
          # setupGitUser: true
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
